server:
  port: 3333

spring:
  application:
    name: Cloud-API-Gateway

  cloud:
    gateway:
      routes:
        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome

        - id: greet-api
          uri: lb://GREET-API
          predicates:
            - Path=/greet

        - id: gpay-api
          uri: lb://GPAY-API
          predicates:
            - Path=/getgpay

        - id: sbi-api
          uri: lb://SBI-API
          predicates:
            - Path=/getsbi
